const formBuilderLang = {
  i18n: {
    override: {
      "en-US": {
        addOption: "Seçenek Ekle",
        allFieldsRemoved: "Tüm alanlar silindi",
        allowMultipleFiles: "Birden fazla dosya yükleme",
        autocomplete: "Otomatik tamamlama",
        button: "Buton",
        cannotBeEmpty: "Bu alan boş bırakılamaz",
        checkboxGroup: "Çoklu Seçim Kutusu",
        checkbox: "Seçim Kutusu",
        checkboxes: "Seçim Kutuları",
        className: "Sınıf Adı",
        clearAllMessage: "Tüm alanları silmek istediğinize emin misiniz?",
        clearAll: "Tümünü Sil",
        close: "Kapat",
        content: "İçerik",
        copy: "Kopyala",
        copyButton: "&#43;",

        copyButtonTooltip: "Kopyala",
        dateField: "Tarih Alanı",
        description: "Açıklama",
        descriptionField: "Açıklama Alanı",
        devMode: "Geliştirici Modu",
        editNames: "Alan Adlarını Düzenle",
        editorTitle: "Form Alanları",
        editXML: "XML'i Düzenle",
        enableOther: "Diğerini Etkinleştir",
        enableOtherMsg: "Diğer seçeneği etkinleştir",
        fieldNonEditable: "Bu alan düzenlenebilir değil.",
        fieldRemoveWarning: "Bu alanı silmek istediğinize emin misiniz?",
        fileUpload: "Dosya Yükleme",
        formUpdated: "Form Güncellendi",
        getStarted: "Form alanları eklemek için buraya tıklayın",
        header: "Başlık",
        hide: "Gizle",
        hidden: "Gizli Alan",
        label: "Etiket",
        labelEmpty: "Alan Etiketi boş bırakılamaz",
        limitRole: "Kullanıcı türüne göre sınırla:",
        mandatory: "Zorunlu",
        maxlength: "Maksimum Uzunluk",
        minOptionMessage: "Bu alan en az 2 seçenek gerektirir",
        name: "Ad",
        no: "Hayır",
        off: "Kapalı",
        on: "Açık",
        option: "Seçenek",
        optional: "isteğe bağlı",
        optionLabelPlaceholder: "Etiket",
        optionValuePlaceholder: "Değer",
        optionEmpty: "Seçenek değeri gereklidir",
        other: "Diğer",
        paragraph: "Paragraf",
        placeholder: "Yer Tut",
        placeholders: {
          value: "Değer",
          label: "Etiket",
          text: "Metin",
          textarea: "Metin Alanı",
          email: "E-posta",
          placeholder: "",
          className: "sınıf-adı",
          password: "Şifre",
        },
        preview: "Önizleme",
        radioGroup: "Radyo Butonları",
        radio: "Radyo Butonu",
        removeMessage: "Alanı Sil",
        remove: "&#215;",
        required: "Zorunlu",
        richText: "Zengin Metin",
        roles: "Kullanıcı Türleri",
        save: "Kaydet",
        selectOptions: "Seçenekler",
        select: "Seçim Kutusu",
        selectColor: "Renk Seç",
        selectionsMessage: "Seçenekleri İzin Ver",
        size: "Boyut",
        sizes: {
          xs: "Çok Küçük",
          sm: "Küçük",
          m: "Orta",
          lg: "Büyük",
        },
        style: "Stil",
        styles: {
          btn: {
            default: "Varsayılan",
            danger: "Tehlike",
            info: "Bilgi",
            primary: "Birincil",
            success: "Başarılı",
            warning: "Uyarı",
          },
        },
        subtype: "Alt Tür",
        text: "Metin",
        textArea: "Metin Alanı",
        toggle: "Aç/Kapa",
        warning: "Uyarı!",
        value: "Değer",
        viewJSON: "{ }",
        viewXML: "&lt;/&gt;",
        yes: "Evet",
        clear: "Temizle",
      },
    },
  },
  disableFields: [
    "autocomplete",
    "checkbox-group",
    "checkbox",
    "date",
    "number",
    "radio-group",

    "hidden",
    "header",
  ],
}
